export var Constants = {
    localIPAddress    : '192.168.0.',
  	myMatApiStartUrl  : 'http://192.168.1.3/start.htm',
    myMatApiIndexUrl  : 'http://192.168.1.3/index.htm',
  	myMatApiUrl       : 'https://healinghouse.life/api/mymat/', //'https://www.esferasoluciones.com/api/mymat/',
    storageKeyLang    : 'mymat_lang',
    storageKeyBubble1 : 'MyMat_bubbleRoutineProgram1',
    storageKeyBubble2 : 'MyMat_bubbleRoutineProgram2',
    storageKeyBubble3 : 'MyMat_bubbleRoutineProgram3',
    storageKeyBubble4 : 'MyMat_bubbleRoutineProgram4',
    storageKeyScrollTop : 'MyMat_scrollTop',
    storageKeyCurrentProgram : 'MyMat_currentProgram',
    deviceInfoKey: 'MyMatDevice',
    test_uuid: 'UUIDTEST-1234-5678-9100-0000AGO19813',
    latestRoutinesKey: 'latestRoutines',
    monthNames: [
        "january", "february", "march",
        "april", "may", "june", "july",
        "August", "September", "October",
        "november", "december"
      ],
    shortTitles       : [
                        'earth-element-upper',
                        'fire-element-upper',
                        'metal-element-upper',
                        'water-element-upper',
                        'wood-element-upper',
                        'gallbladder-meridian-upper',
                        'kidney-meridian-upper',
                        'heart-meridian-upper',
                        'large-intestine-meridian-upper',
                        'liver-meridian-upper',
                        'lung-meridian-upper',
                        'pericardium-meridian-upper',
                        'small-intestine-meridian-upper',
                        'spleen-pancreas-meridian-upper',
                        'stomach-meridian-upper',
                        'triple-warmer-meridian-upper',
                        'urinary-bladder-meridian-upper'
                      ]
};
